<a href="https://colab.research.google.com/github/De-Las-Alas/58013-LinearAlgebra/blob/main/Determinant%20of%20Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Example1
Evaluate the 2x2 Determinant
[4,-3]
[2,5]

In [17]:
import numpy as jk

A = jk.array([
    [4,-3],
    [2,5]
])
print(f'Array A:\n{A}')

B = jk.linalg.det(A)

print(f'\nThe Array A Determinant is: {int(B)}')

Array A:
[[ 4 -3]
 [ 2  5]]

The Array A Determinant is: 25


#Example2
Evaluate the 3x3 Determinant [2,3,-5][7,1,-2][-3,4,1]

In [18]:
C = jk.array([
    [2,3,-5],
    [7,1,-2],
    [-3,4,1]
])
print(f'Array C:\n{C}')

D = jk.linalg.det(C)

print(f'\nThe Array C Determinant is: {int(D)}')

Array C:
[[ 2  3 -5]
 [ 7  1 -2]
 [-3  4  1]]

The Array C Determinant is: -140


#Example3
Evaluate [4,7,8],
   [-9,0,0],
    [2,3,4]

In [22]:
E = jk.array([
    [4,7,8],
   [-9,0,0],
    [2,3,4]
])
print(f'Array E:\n{E}')

F = jk.linalg.det(E)

print(f'\nThe Array E Determinant is: {int(F)}')

Array E:
[[ 4  7  8]
 [-9  0  0]
 [ 2  3  4]]

The Array E Determinant is: 36


#Example4
Evaluate [1,2,-1],[4,6,-2],[-1,3,3]

In [23]:
G = jk.array([
    [1,2,-1],
    [4,6,-2],
   [-1,3,3]
])
print(f'Array G:\n{G}')

H = jk.linalg.det(G)

print(f'\nThe Array G Determinant is: {int(H)}')

Array G:
[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]

The Array G Determinant is: -13
