<a href="https://colab.research.google.com/github/De-Las-Alas/58013-LinearAlgebra/blob/main/Python%20Exercise%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Code the following vector operation and solve them using the given vector values.

#A = ([[-0.4],[4.3],[-0.6]])
#B = ([-0.2,0.2,1])
#C = ([-0.2,2.1,-1.5])

#Create a program flowchart for your algorithm and explain it in your methodology. In yourresults, compare your answer to the expected output, visualize, and explain the resulting vectorusing a 3D plot.

In [12]:
#Importing arrays
import numpy as np

#Array matrices
A = np.array([
    [-0.4],
    [4.3],
    [-0.6]
])
B = np.array([-0.2,0.2,1])
C = np.array([-0.2,2.1,-1.5])

#Operations

#Addition
sum = A+B+C
print(f"The sum of the three arrays are:\n{sum}")

#Subtraction
diff = A-B-C
print(f"The difference of the three three arrays are:\n{diff}")

#Multiplication
prod = A*B*C
print(f"The product of the three arrays are:\n{prod}")

#Division
quot = A/B/C
print(f"The quotient of the three arrays are:\n{quot}")

The sum of the three arrays are:
[[-0.8  1.9 -0.9]
 [ 3.9  6.6  3.8]
 [-1.   1.7 -1.1]]
The difference of the three three arrays are:
[[ 0.  -2.7  0.1]
 [ 4.7  2.   4.8]
 [-0.2 -2.9 -0.1]]
The product of the three arrays are:
[[-0.016 -0.168  0.6  ]
 [ 0.172  1.806 -6.45 ]
 [-0.024 -0.252  0.9  ]]
The quotient of the three arrays are:
[[-10.          -0.95238095   0.26666667]
 [107.5         10.23809524  -2.86666667]
 [-15.          -1.42857143   0.4       ]]
