<a href="https://colab.research.google.com/github/De-Las-Alas/58013-LinearAlgebra/blob/main/Python%20Exercise%209.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [3]:
## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.

B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

#Coding Activity 9
Prove and implement the remaining 6 matrix multiplication properties. You may create your ownmatrices in which their shapes should not be lower than (3,3). In your methodology, createindividual flowcharts for each property and discuss the property you would then present yourproofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [33]:
import numpy as np

C = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
D = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])
E = np.array([
    [7,4,1],
    [8,5,2],
    [9,6,3]
])

#calculations
#Associative property
F = C*(D*E)
G = (C*D)*E
#Closure property
H = np.dot(C,D)
#Distributive property
I = C*(D+E)
J = (C*D)+(C*E)
#Identity property
K = np.eye(3,3)
L = np.dot(K,C)
#Scalar property
M = C*D
#Zero property
N = np.zeros((3,3))
O = np.dot(C,N)

#output
print(f'Associative Property:\n C*(D*E) =\n{F}\n Is the same as\n (C*D)*E =\n{G}')
print(f'\nClosre Property:\n np.dot(C,D) =\n{H}')
print(f'\nDistributive Property:\n C*(D+E) =\n{I}\n Is the same as\n (C*D)+(C*E) =\n{J}')
print(f'\nIdentity Property:\nif\n{E}\nis multiplied to\n{K}\nthen\n{L}')
print(f'\nScalar Property:\nC*D =\n{M}')
print(f'\nZero Property:\nif\n{C}\nis multiplied to\n{N}\nthen\n{O}')

Associative Property:
 C*(D*E) =
[[ 63  64  21]
 [192 125  48]
 [189  96  27]]
 Is the same as
 (C*D)*E =
[[ 63  64  21]
 [192 125  48]
 [189  96  27]]

Closre Property:
 np.dot(C,D) =
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Distributive Property:
 C*(D+E) =
[[16 24 24]
 [56 50 36]
 [84 64 36]]
 Is the same as
 (C*D)+(C*E) =
[[16 24 24]
 [56 50 36]
 [84 64 36]]

Identity Property:
if
[[7 4 1]
 [8 5 2]
 [9 6 3]]
is multiplied to
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
then
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Scalar Property:
C*D =
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Zero Property:
if
[[1 2 3]
 [4 5 6]
 [7 8 9]]
is multiplied to
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
then
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
