<a href="https://colab.research.google.com/github/De-Las-Alas/58013-LinearAlgebra/blob/main/Vector%20Spaces%20%26%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Let's Try This Code

In [3]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print("Vector A is,", A)
print("Vector B is,", B)

Vector A is, [4 3]
Vector B is, [ 2 -5]


#Matrix
Let’s try this code:

In [39]:
### Checking shapes
### Shapes tells us how many rows and columns are there
import numpy as np

ball1 = np.array([1, 2, 3])
ball2 = np.array([0, 1, -1])

b1 = np.shape(ball1)
b2 = np.shape(ball2)

pool = np.shape([ball1,ball2])

z = b1 + b2

#Shape of the Matrix
print("Shape of Ball 1 is,", b1, ", and the Shape of Ball 2 is,", b2, ".")
print("Ball 1 Matrix:", ball1)
print("Ball 2 Matrix:", ball2)
print("The number of rows and columns respectively are:", pool)
print(z)

Shape of Ball 1 is, (3,) , and the Shape of Ball 2 is, (3,) .
Ball 1 Matrix: [1 2 3]
Ball 2 Matrix: [ 0  1 -1]
The number of rows and columns respectively are: (2, 3)
(3, 3)


#Column Vector

In [49]:
import numpy as np

ball1 = np.array([[1], [2], [3]])
ball2 = np.array([[0], [1], [-1]])

print(ball1,"\n")

print(ball2)

[[1]
 [2]
 [3]] 

[[ 0]
 [ 1]
 [-1]]


#Row Vector

In [50]:
import numpy as np

ball1 = np.array([1, 2, 3])
ball2 = np.array([0, 1, -1])

print(ball1,"\n")

print(ball2)

[1 2 3] 

[ 0  1 -1]


#Addition
Example:

In [46]:
import numpy as np

A = np.array([[4], [3]])
B = np.array([[2], [-5]])

R1 = np.add(A,B)

C = np.array([4, 3])
D = np.array([2, -5])

R2 = np.add(C,D)

print("Column form:\n", R1)
print("\nRow form:\n", R2)

Column form:
 [[ 6]
 [-2]]

Row form:
 [ 6 -2]


#Subtraction
Example:

In [47]:
import numpy as np

A = np.array([[4], [3]])
B = np.array([[2], [-5]])

R1 = np.subtract(A,B)

C = np.array([4, 3])
D = np.array([2, -5])

R2 = np.subtract(C,D)

print("Column form:\n", R1)
print("\nRow form:\n", R2)

Column form:
 [[2]
 [8]]

Row form:
 [2 8]


#Scalar
Let’s try this code:

In [98]:
A = np.array([4, 3])
B = np.array([[2], [-5]])
C = np.array([1, 5, 8, 9])
S = [2]

T = A*B
U = 5*C
V = S*A

print("T:",T, "\n")
print("U:", U, "\n")
print("V:",V)

T: [[  8   6]
 [-20 -15]] 

U: [ 5 25 40 45] 

V: [8 6]


#Vector Multiplication
Let’s code this:

In [96]:
import numpy as np
#initialize arrays
#all rows
A = np.array([2, 3])
B = np.array([1, 7])
#different dimensions
C = np.array([4, 3])
D = np.array([[2], [-5]])
#all columns
E = np.array([[4], [2]])
F = np.array([[2], [-7]])
#compute cross product
output1 = np.cross(A, B)
#compute dot product
output2 = np.dot(A, B)
output3 = np.dot(C, D)
V1 = A*B
V2 = C*D
V3 = E*F

print("npCross Row A & Row B:", output1, "\n")
print("npDot Row A & Row B:", output2, "\n")
print("Dot Product A & B:", V1, "\n")
print("npDot Rom C & Column D:", output3, "\n")
print("Dot Product C & D:", V2, "\n")
print("Dot Product E & F:", V3)

npCross Row A & Row B: 11 

npDot Row A & Row B: 23 

Dot Product A & B: [ 2 21] 

npDot Rom C & Column D: [-7] 

Dot Product C & D: [[  8   6]
 [-20 -15]] 

Dot Product E & F: [[  8]
 [-14]]


#Identity Matirx

In [97]:
import numpy as np

A = np.eye(2, 2)
B = np.eye(3, 3)
C = np.eye(3, 2)
D = np.eye(3, 4)

print(A, "\n")
print(B, "\n")
print(C, "\n")
print(D)

[[1. 0.]
 [0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0.]
 [0. 1.]
 [0. 0.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


#Zero Matrix

In [90]:
import numpy as np
A = np.zeros((6, 6))

print(A)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#Full Matrix

In [89]:
import numpy as np
A = np.full((4, 4), 7)
B = np.full((5, 5), 6)

print(A, "\n")
print(B)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]] 

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


#Transpose Matrix

In [95]:
import numpy as np
A = np.array([2,2])
B = np.array([[5],[4]])
print(A, "\n")
print(B, "\n")

C = A*B
print(C, "\n")

f = np.transpose(C)
print(f)

[2 2] 

[[5]
 [4]] 

[[10 10]
 [ 8  8]] 

[[10  8]
 [10  8]]
